const appname = "EcommerceApp";
const appversion = "Version 1.0.0";
const credits = "Developed by: Samra";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*****";
const retypePassowrd = "Retype Password";
const name = "Name";
const nameHint = "Samra Asif";
const forgotPassword = "Forgot Password";
const login = " Login";
const signup = "Sign Up";
const createNewAccount = "or,create a new account";
const loginWith = "Login With";
const resgisterWithPhoneNumber="or,register with phone number";
const privacyPolicy = "Privacy Policy";
const termsAndConditions = "Terms and Conditions";
const alreadyHaveAnAccount = "Already have an account?";
const home="Home",categories="Categories",cart="Cart",account="Account";

const searchanything="Search Anything";